r"""
pull_heavy_sources.py

Re-pull all source layers for relocated ("heavy") SADs whose canvas was
regenerated by boundary_update.py. For each district this fetches, keyed to the
district's NEW source/image_extent.geojson:

  buildings.geojson   OSM building footprints      (osmnx)
  highways.geojson    OSM roads (lines, w/ lanes)  (osmnx)
  parking.geojson     OSM parking (lots + garages) (osmnx)
  parks.geojson       OSM parks / green space      (osmnx)
  POIs                Overture Places              (module_overture_places)

WHY
    The pipeline has no live puller; it consumes static source/*.geojson files
    that were acquired for the OLD canvas. When a boundary moved enough to
    relocate the canvas, those files no longer cover the area. This regenerates
    them for the new canvas so the pipeline can re-run.

SCHEMA NOTES (so downstream modules stay happy)
    - module_3b splits parking into surface vs structure on the `building` tag,
      and computes road widths from `highway` + `lanes`. Those columns are
      preserved here.
    - The viewer colors buildings by their OSM `building` tag; preserved.
    - module_03 REQUIRES `primary_category` + `taxonomy_hierarchy` on the POI
      file (it does its own Rossetti rollup). module_overture_places emits
      `category` (+ a pre-rolled `rossetti_category`). We therefore rename
      category -> primary_category and synthesize taxonomy_hierarchy from the
      module's own top-level inference, so the POI file takes the SAME code path
      as every other district (this is exactly what the drawn districts got
      wrong: they lacked these columns and failed module_03).

OUTPUTS land in:
    <data>/<sad>/source/{buildings,highways,parking,parks}.geojson
    <data>/<sad>/03_ROD-Search-Tool/ROD_Search/overture_places.geojson  (POIs)
Existing files are backed up to *_prev.geojson once.

USAGE
    python pull_heavy_sources.py --data-dir "<data>" ^
        --sads "16_Mission-Rock_San-Francisco-CA,18_Ballpark-Village_St-Louis-MO" ^
        --code-dir "<code>"        # so module_overture_places is importable
    # skip POIs (OSM layers only):           --no-pois
    # skip OSM (POIs only):                  --no-osm
    # dry run (report extents, fetch nothing): --dry-run
"""
from __future__ import annotations
import argparse
import importlib.util
import json
import random
import sys
import time
from pathlib import Path

import geopandas as gpd
import pandas as pd

ROD_CONFIG_DEFAULT = Path.home() / '.rod_search_tool' / 'config.json'

# Overpass throttles aggressively (HTTP 429 / 504). Retry with exponential
# backoff + jitter so a transient throttle doesn't poison a layer with a false
# zero. Raises the last error only after all attempts are exhausted.
MAX_RETRIES = 5
BASE_BACKOFF = 8.0   # seconds; grows 8,16,32,64,...


def _is_throttle(err) -> bool:
    s = str(err).lower()
    return ('429' in s or '504' in s or 'too many requests' in s
            or 'timeout' in s or 'timed out' in s or 'gateway' in s
            or 'remote end closed' in s or 'connection' in s)


def with_retry(fn, what: str):
    """Call fn() with exponential backoff on throttle/transient errors."""
    last = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            return fn()
        except Exception as e:  # noqa: BLE001
            last = e
            if attempt == MAX_RETRIES or not _is_throttle(e):
                raise
            wait = BASE_BACKOFF * (2 ** (attempt - 1)) + random.uniform(0, 4)
            print(f"        [retry {attempt}/{MAX_RETRIES}] {what}: {type(e).__name__} "
                  f"-- backing off {wait:.0f}s")
            time.sleep(wait)
    raise last  # pragma: no cover


def load_rod_categories(config_path: Path):
    """Return the ROD tool's Overture category allow-list, or None."""
    try:
        cfg = json.loads(config_path.read_text(encoding='utf-8'))
    except Exception:
        return None
    cats = cfg.get('categories')
    return list(cats) if cats else None


def dedup_pois(features, dist_m: float = 25.0):
    """Drop near-duplicate POIs: same normalized name within dist_m.
    Overture carries multiple records for one establishment; this collapses
    them. Points with no name are kept as-is (can't safely match)."""
    if not features:
        return features
    import math
    from collections import defaultdict
    def norm(nm): return (nm or '').strip().lower()
    # group by name; unnamed kept verbatim
    groups = defaultdict(list)
    kept = []
    for f in features:
        nm = norm(f['properties'].get('name'))
        if not nm:
            kept.append(f)
        else:
            groups[nm].append(f)
    # within each name group, greedily keep points > dist_m apart
    # convert metres -> degrees roughly (lat); fine for a small canvas
    deg = dist_m / 111320.0
    for nm, fs in groups.items():
        anchors = []
        for f in fs:
            x, y = f['geometry']['coordinates']
            dup = False
            for ax, ay in anchors:
                # local equirectangular distance in degrees
                dx = (x - ax) * math.cos(math.radians(y))
                if math.hypot(dx, y - ay) <= deg:
                    dup = True
                    break
            if not dup:
                anchors.append((x, y))
                kept.append(f)
    return kept


# ── OSM tag filters per layer ────────────────────────────────────────────────
OSM_TAGS = {
    'buildings': {'building': True},
    'highways':  {'highway': True},
    # parking: surface lots (amenity=parking, no building tag) AND structures
    # (building in garage/parking) -- module_3b uses the `building` tag to split.
    'parking':   {'amenity': 'parking',
                  'building': ['garage', 'garages', 'parking', 'carport',
                               'parking_entrance']},
    'parks':     {'leisure': ['park', 'garden', 'nature_reserve',
                              'recreation_ground', 'common'],
                  'landuse': ['recreation_ground', 'grass', 'village_green']},
}
# columns worth keeping per layer (others dropped to keep GeoJSON clean);
# geometry always kept. Missing columns are simply skipped.
KEEP_COLS = {
    'buildings': ['building', 'name', 'height', 'building:levels', 'amenity'],
    'highways':  ['highway', 'lanes', 'name', 'oneway', 'maxspeed', 'surface'],
    'parking':   ['amenity', 'building', 'parking', 'access', 'name'],
    'parks':     ['leisure', 'landuse', 'name'],
}
# geometry types to retain per layer
GEOM_KIND = {
    'buildings': ('Polygon', 'MultiPolygon'),
    'highways':  ('LineString', 'MultiLineString'),
    'parking':   ('Polygon', 'MultiPolygon'),
    'parks':     ('Polygon', 'MultiPolygon'),
}


def _import_overture(code_dir: Path):
    """Import module_overture_places from the code dir."""
    path = code_dir / 'module_overture_places.py'
    if not path.exists():
        return None
    spec = importlib.util.spec_from_file_location('module_overture_places', path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules['module_overture_places'] = mod
    spec.loader.exec_module(mod)
    return mod


def _clean_for_geojson(gdf: gpd.GeoDataFrame, layer: str) -> gpd.GeoDataFrame:
    """Keep whitelisted cols + geometry, coerce list-valued cells to strings,
    filter to the layer's geometry kinds, drop empties."""
    if gdf is None or gdf.empty:
        return gpd.GeoDataFrame(geometry=[], crs='EPSG:4326')
    gdf = gdf[gdf.geometry.notna() & ~gdf.geometry.is_empty].copy()
    kinds = GEOM_KIND[layer]
    gdf = gdf[gdf.geom_type.isin(kinds)].copy()
    keep = [c for c in KEEP_COLS[layer] if c in gdf.columns]
    gdf = gdf[keep + ['geometry']].copy()
    # osmnx can return list-valued tag cells; GeoJSON can't serialize lists.
    for c in keep:
        gdf[c] = gdf[c].apply(lambda v: ';'.join(map(str, v)) if isinstance(v, list) else v)
    if gdf.crs is None:
        gdf = gdf.set_crs('EPSG:4326')
    else:
        gdf = gdf.to_crs('EPSG:4326')
    return gdf.reset_index(drop=True)


def _backup_once(path: Path):
    if path.exists():
        bk = path.with_name(path.stem + '_prev' + path.suffix)
        if not bk.exists():
            bk.write_bytes(path.read_bytes())


def _existing_count(path: Path):
    """Feature count of an existing geojson, or None if absent/unreadable."""
    if not path.exists():
        return None
    try:
        return len(json.loads(path.read_text()).get('features', []))
    except Exception:
        return None


def pull_osm_layers(ox, extent_poly, source_dir: Path, dry_run: bool,
                    skip_existing: bool = False) -> dict:
    out = {}
    for layer, tags in OSM_TAGS.items():
        dst = source_dir / f'{layer}.geojson'
        # idempotent: skip a layer that already has real (non-empty) data, so a
        # re-run after a partial throttle only re-fetches what failed.
        if skip_existing:
            n = _existing_count(dst)
            if n is not None and n > 0:
                out[layer] = f'{n} features (kept, already present)'
                continue
        try:
            feats = with_retry(lambda: ox.features_from_polygon(extent_poly, tags),
                               f'{layer}')
        except Exception as e:
            # do NOT write anything on failure -- leaving a false empty file is
            # exactly the throttle-poisoning bug we want to avoid. Preserve any
            # prior file so a re-run can still skip/repair.
            out[layer] = f'OSM ERROR (left unwritten): {e}'
            continue
        clean = _clean_for_geojson(feats, layer)
        out[layer] = f'{len(clean)} features'
        if dry_run:
            continue
        _backup_once(dst)
        if len(clean):
            clean.to_file(dst, driver='GeoJSON')
        else:
            # genuine empty (fetch succeeded, area truly has none of this layer)
            dst.write_text('{"type":"FeatureCollection","features":[]}')
    return out


def pull_pois(overture_mod, extent_geom_geojson: dict, sad_dir: Path,
              dry_run: bool, categories=None, dedup_dist: float = 25.0,
              skip_existing: bool = False) -> str:
    if overture_mod is None:
        return 'SKIP (module_overture_places not importable; pass --code-dir)'
    if skip_existing:
        dst0 = sad_dir / '03_ROD-Search-Tool' / 'ROD_Search' / 'overture_places.geojson'
        n = _existing_count(dst0)
        if n is not None and n > 0:
            return f'{n} POIs (kept, already present)'
    try:
        fc = with_retry(
            lambda: overture_mod.places_in_polygon(extent_geom_geojson, categories=categories),
            'overture POIs')
    except Exception as e:
        return f'Overture ERROR (left unwritten): {e}'
    feats = fc.get('features', [])
    n_raw = len(feats)
    if dedup_dist and dedup_dist > 0:
        feats = dedup_pois(feats, dedup_dist)
    n_dedup = len(feats)
    # Reshape to module_03's expected schema: primary_category + taxonomy_hierarchy.
    infer = getattr(overture_mod, '_infer_top_level', lambda x: None)
    for f in feats:
        p = f['properties']
        cat = p.get('category')
        p['primary_category'] = cat
        top = infer(cat) if cat else None
        # module_03._get_top_level reads the first element of this array
        p['taxonomy_hierarchy'] = [top] if top else []
        # leave name/confidence/id/rossetti_category in place (harmless extras)
    if dry_run:
        return f'{n_raw} raw -> {n_dedup} after dedup (dry-run, not written)'
    rod_dir = sad_dir / '03_ROD-Search-Tool' / 'ROD_Search'
    rod_dir.mkdir(parents=True, exist_ok=True)
    dst = rod_dir / 'overture_places.geojson'
    _backup_once(dst)
    dst.write_text(json.dumps({'type': 'FeatureCollection', 'features': feats}))
    return f'{n_raw} raw -> {n_dedup} after dedup -> {dst.relative_to(sad_dir)}'


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--data-dir', type=Path, required=True)
    ap.add_argument('--sads', type=str, required=True,
                    help='Comma-separated SAD folder names (the heavy districts).')
    ap.add_argument('--code-dir', type=Path, default=Path(__file__).parent,
                    help='Folder containing module_overture_places.py (default: '
                         "this script's directory).")
    ap.add_argument('--no-osm', action='store_true', help='Skip OSM layers.')
    ap.add_argument('--no-pois', action='store_true', help='Skip Overture POIs.')
    ap.add_argument('--rod-config', type=Path, default=ROD_CONFIG_DEFAULT,
                    help='ROD config.json holding the category allow-list '
                         '(default: ~/.rod_search_tool/config.json).')
    ap.add_argument('--no-category-filter', action='store_true',
                    help='Pull ALL Overture categories (not just the ROD list).')
    ap.add_argument('--dedup-dist', type=float, default=25.0,
                    help='Dedup radius in metres for same-name POIs (default 25).')
    ap.add_argument('--no-dedup', action='store_true', help='Disable POI dedup.')
    ap.add_argument('--dry-run', action='store_true')
    ap.add_argument('--skip-existing', action='store_true',
                    help='Skip layers/POIs that already have non-empty data '
                         '(use when re-running after a partial throttle).')
    ap.add_argument('--max-retries', type=int, default=MAX_RETRIES,
                    help=f'Overpass/Overture retry attempts (default {MAX_RETRIES}).')
    args = ap.parse_args()
    globals()['MAX_RETRIES'] = max(1, args.max_retries)

    data_dir = args.data_dir.resolve()
    if not data_dir.exists():
        sys.exit(f"data dir does not exist: {data_dir}")
    sads = [s.strip() for s in args.sads.split(',') if s.strip()]
    if not sads:
        sys.exit("No SADs given.")

    ox = None
    if not args.no_osm:
        try:
            import osmnx as ox  # noqa
        except ImportError:
            sys.exit("osmnx not installed. pip install osmnx --break-system-packages")
        # be polite to Overpass: longer timeout, modest pause between queries.
        try:
            ox.settings.requests_timeout = 180
            ox.settings.overpass_rate_limit = True
        except Exception:
            pass  # older/newer osmnx may name these differently; non-fatal

    overture_mod = None if args.no_pois else _import_overture(args.code_dir)
    rod_categories = None
    if not args.no_pois and not args.no_category_filter:
        rod_categories = load_rod_categories(args.rod_config)
        if rod_categories:
            print(f"[info] POI category allow-list: {len(rod_categories)} categories "
                  f"from {args.rod_config}")
        else:
            print(f"[warn] no category allow-list found at {args.rod_config}; "
                  f"pulling ALL categories (expect a large POI count)")
    if not args.no_pois and overture_mod is None:
        print(f"[warn] module_overture_places.py not found in {args.code_dir}; "
              f"POIs will be skipped. Use --code-dir to point at it.\n")

    print(f"{'DRY-RUN: ' if args.dry_run else ''}re-pulling sources for "
          f"{len(sads)} heavy district(s)\n")

    for sad in sads:
        sad_dir = data_dir / sad
        source = sad_dir / 'source'
        ext = source / 'image_extent.geojson'
        print(f"  {sad}")
        if not ext.exists():
            print(f"      ERROR no source/image_extent.geojson -- run boundary_update first")
            continue
        ext_gdf = gpd.read_file(ext).to_crs('EPSG:4326')
        extent_poly = ext_gdf.geometry.iloc[0]
        extent_geojson = json.loads(gpd.GeoSeries([extent_poly], crs='EPSG:4326').to_json())
        extent_geom = extent_geojson['features'][0]['geometry']
        b = extent_poly.bounds
        print(f"      canvas bbox: [{b[0]:.5f}, {b[1]:.5f}, {b[2]:.5f}, {b[3]:.5f}]")

        if not args.no_osm:
            res = pull_osm_layers(ox, extent_poly, source, args.dry_run, skip_existing=args.skip_existing)
            for layer in ('buildings', 'highways', 'parking', 'parks'):
                print(f"      {layer:9s}: {res.get(layer, '-')}")
        if not args.no_pois:
            print(f"      pois     : {pull_pois(overture_mod, extent_geom, sad_dir, args.dry_run, categories=rod_categories, dedup_dist=(0 if args.no_dedup else args.dedup_dist), skip_existing=args.skip_existing)}")

    print(f"\n{'DRY-RUN complete (nothing written).' if args.dry_run else 'Done.'}")
    if not args.dry_run:
        print("Next: re-run the pipeline for these districts (Module 1 onward) so "
              "the new canvas + layers propagate, e.g.:\n"
              "  python batch_run_pipeline.py --data-dir <data> --stage per-sad "
              "--force --sads <these districts>")


if __name__ == '__main__':
    main()
